services:
  dog-api:
    build:
      context: ./dog-api
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "8080"   # internal only
    networks:
      - app-net

  nginx:
    image: nginx:1.27-alpine
    container_name: ingress-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - dog-api
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
