spring:
  application:
    name: human-api
  datasource:
    url: jdbc:postgresql://localhost:5432/humandb
    username: postgres
    password: p@ssw0rd1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
      properties:
      hibernate:
        format_sql: true